// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using backend.Data;

#nullable disable

namespace backend.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.17");

            modelBuilder.Entity("backend.Models.Database.Product", b =>
                {
                    b.Property<int>("PKProduct")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("pk_product");

                    b.Property<bool?>("Enable")
                        .HasColumnType("INTEGER")
                        .HasColumnName("enable");

                    b.Property<int?>("FKCreatedBy")
                        .HasColumnType("INTEGER")
                        .HasColumnName("fk_created_by");

                    b.Property<int?>("FKUnit")
                        .HasColumnType("INTEGER")
                        .HasColumnName("fk_unit");

                    b.Property<int?>("FKUpdatedBy")
                        .HasColumnType("INTEGER")
                        .HasColumnName("fk_updated_by");

                    b.Property<float>("MinPrice")
                        .HasColumnType("REAL")
                        .HasColumnName("min_price");

                    b.Property<float>("MinQuantity")
                        .HasColumnType("REAL")
                        .HasColumnName("min_quantity");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<float>("Price")
                        .HasColumnType("REAL")
                        .HasColumnName("price");

                    b.Property<float>("Quantity")
                        .HasColumnType("REAL")
                        .HasColumnName("quantity");

                    b.Property<DateTime?>("RegisterDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("register_date");

                    b.Property<string>("SerialNumber")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("serial_number");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("update_date");

                    b.HasKey("PKProduct")
                        .HasName("pk_product");

                    b.HasIndex("FKCreatedBy")
                        .HasDatabaseName("ix_product_fk_created_by");

                    b.HasIndex("FKUnit")
                        .HasDatabaseName("ix_product_fk_unit");

                    b.HasIndex("FKUpdatedBy")
                        .HasDatabaseName("ix_product_fk_updated_by");

                    b.ToTable("product", (string)null);
                });

            modelBuilder.Entity("backend.Models.Database.Sale", b =>
                {
                    b.Property<int>("PKSale")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("pk_sale");

                    b.Property<float>("ChangeAmount")
                        .HasColumnType("REAL")
                        .HasColumnName("change_amount");

                    b.Property<float>("DiscountAmount")
                        .HasColumnType("REAL")
                        .HasColumnName("discount_amount");

                    b.Property<bool>("Enable")
                        .HasColumnType("INTEGER")
                        .HasColumnName("enable");

                    b.Property<int>("FKUser")
                        .HasColumnType("INTEGER")
                        .HasColumnName("fk_user");

                    b.Property<float>("ReceivedAmount")
                        .HasColumnType("REAL")
                        .HasColumnName("received_amount");

                    b.Property<DateTime?>("RegisterDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("register_date");

                    b.Property<float>("Subtotal")
                        .HasColumnType("REAL")
                        .HasColumnName("subtotal");

                    b.Property<float>("Total")
                        .HasColumnType("REAL")
                        .HasColumnName("total");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("update_date");

                    b.HasKey("PKSale")
                        .HasName("pk_sale");

                    b.HasIndex("FKUser")
                        .HasDatabaseName("ix_sale_fk_user");

                    b.ToTable("sale", (string)null);
                });

            modelBuilder.Entity("backend.Models.Database.SaleDetail", b =>
                {
                    b.Property<int>("PKSaleDetail")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("pk_sale_detail");

                    b.Property<float>("Discount")
                        .HasColumnType("REAL")
                        .HasColumnName("discount");

                    b.Property<int>("FKProduct")
                        .HasColumnType("INTEGER")
                        .HasColumnName("fk_product");

                    b.Property<int>("FKSale")
                        .HasColumnType("INTEGER")
                        .HasColumnName("fk_sale");

                    b.Property<float>("Quantity")
                        .HasColumnType("REAL")
                        .HasColumnName("quantity");

                    b.Property<float>("TotalProduct")
                        .HasColumnType("REAL")
                        .HasColumnName("total_product");

                    b.Property<float>("UnitPrice")
                        .HasColumnType("REAL")
                        .HasColumnName("unit_price");

                    b.HasKey("PKSaleDetail")
                        .HasName("pk_sale_detail");

                    b.HasIndex("FKProduct")
                        .HasDatabaseName("ix_sale_detail_fk_product");

                    b.HasIndex("FKSale")
                        .HasDatabaseName("ix_sale_detail_fk_sale");

                    b.ToTable("sale_detail", (string)null);
                });

            modelBuilder.Entity("backend.Models.Database.Unit", b =>
                {
                    b.Property<int>("PKUnit")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("pk_unit");

                    b.Property<string>("Abbreviation")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("abbreviation");

                    b.Property<bool>("Enable")
                        .HasColumnType("INTEGER")
                        .HasColumnName("enable");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<DateTime?>("RegisterDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("register_date");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("update_date");

                    b.HasKey("PKUnit")
                        .HasName("pk_unit");

                    b.ToTable("unit", (string)null);
                });

            modelBuilder.Entity("backend.Models.Database.User", b =>
                {
                    b.Property<int>("PKUser")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("pk_user");

                    b.Property<bool>("Enable")
                        .HasColumnType("INTEGER")
                        .HasColumnName("enable");

                    b.Property<string>("Lastname")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("lastname");

                    b.Property<string>("Mail")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("mail");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("password");

                    b.Property<DateTime?>("RegisterDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("register_date");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("role");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("update_date");

                    b.HasKey("PKUser")
                        .HasName("pk_user");

                    b.ToTable("user", (string)null);
                });

            modelBuilder.Entity("backend.Models.Database.Product", b =>
                {
                    b.HasOne("backend.Models.Database.User", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("FKCreatedBy")
                        .HasConstraintName("fk_product_user_fk_created_by");

                    b.HasOne("backend.Models.Database.Unit", "Unit")
                        .WithMany()
                        .HasForeignKey("FKUnit")
                        .HasConstraintName("fk_product_unit_fk_unit");

                    b.HasOne("backend.Models.Database.User", "UpdatedBy")
                        .WithMany()
                        .HasForeignKey("FKUpdatedBy")
                        .HasConstraintName("fk_product_user_fk_updated_by");

                    b.Navigation("CreatedBy");

                    b.Navigation("Unit");

                    b.Navigation("UpdatedBy");
                });

            modelBuilder.Entity("backend.Models.Database.Sale", b =>
                {
                    b.HasOne("backend.Models.Database.User", "User")
                        .WithMany()
                        .HasForeignKey("FKUser")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_sale_user_fk_user");

                    b.Navigation("User");
                });

            modelBuilder.Entity("backend.Models.Database.SaleDetail", b =>
                {
                    b.HasOne("backend.Models.Database.Product", "Product")
                        .WithMany()
                        .HasForeignKey("FKProduct")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_sale_detail_product_fk_product");

                    b.HasOne("backend.Models.Database.Sale", "Sale")
                        .WithMany("SaleDetails")
                        .HasForeignKey("FKSale")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_sale_detail_sale_fk_sale");

                    b.Navigation("Product");

                    b.Navigation("Sale");
                });

            modelBuilder.Entity("backend.Models.Database.Sale", b =>
                {
                    b.Navigation("SaleDetails");
                });
#pragma warning restore 612, 618
        }
    }
}
